models:
  - name: products
    description: |
      Product dimension table. The grain of the table is one row per product.
    access: protected
    group: finance
    config:
      contract:
        enforced: true
    columns:
      - name: product_id
        meta:
          dimension:
            type: string
      - name: product_name
        meta:
          dimension:
            type: string
      - name: product_type
        meta:
          dimension:
            type: string
      - name: product_description
        meta:
          dimension:
            type: string
      - name: product_price
        meta:
          dimension:
            type: number
      - name: is_food_item
        meta:
          dimension:
            type: boolean
      - name: is_drink_item
        meta:
          dimension:
            type: boolean